design:
    end_duration: 100000
    fix_movie_interval: 0
    n_trials: 1
    start_duration: 100000
eyetracker:
    address: 100.1.1.1
    dot_size: 0.1
    options:
        automatic_calibration_pacing: 1000
        autothreshold_click: true
        autothreshold_repeat: true
        binocular_enabled: false
        calibration_area_proportion: 0.4 0.4
        calibration_type: HV13
        enable_automatic_calibration: true
        enable_camera_position_detect: true
        enable_search_limits: true
        file_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,MESSAGE,BUTTON,INPUT
        heuristic_filter: 2
        link_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,BUTTON
        link_sample_data: LEFT,RIGHT,GAZE,GAZERES,AREA,STATUS,HTARGET
        pupil_size_diameter: true
        sample_rate: 1000
        track_search_limits: true
        validation_area_proportion: 0.4 0.4
        x_gaze_constraint: AUTO
        y_gaze_constraint: AUTO
monitor:
    distance: 165
    gamma: 0.454545454545
    name: 7T
    verbose: true
    width: 69
mouse:
    visible: false
mri:
    TA: 2.0
    TR: 2.0
    simulate: false
    skip: 0
    sound: false
    sync: t
    volumes: 10
paths:
    stimuli_path: /Users/shufanzhang/AOT_stimuli/HCPfinals
    stimuli_path_spinoza1: /experiments/knapen_aot/AOT/AOT_stimuli/HCPfinals
    stimuli_path_spinoza2: /experiments/AOT/AOT_stimuli/HCPfinals
preferences:
    general:
        audioLib: sounddevice
        units: deg
stimuli:
    aperture_radius: 10
    fix_color:
    - 1
    - 1
    - 1
    fix_line_width: 1.5
    fix_radius: 6
    movie_files:
    - run_01.mp4
    - run_02.mp4
    - run_03.mp4
    - run_04.mp4
    - run_05.mp4
    - run_06.mp4
    - run_07.mp4
    - run_08.mp4
    movie_size_pix:
    - 1536
    - 1080
    shrink_factor: 0.7
various:
    button_size: 2
    buttons:
    - j
    - k
    - l
    - semicolon
    piechart_width: 1
    text_height: 22.5
    text_width: 14
window:
    color:
    - -1
    - -1
    - -1
    fullscr: true
    pos:
    - 0
    - 0
    screen: 1
    size:
    - 1920
    - 1080
    units: pix
    waitBlanking: true
